export const ProductsAdvertisementOnHeroldFAQBlock = () => {
    return (
        <>
            <div class="faq container">
                <div class="title-head">
                    <h2 _msttexthash="614237" _msthash="182">Frequently Asked Questions</h2>
                    <h3 _msttexthash="3614143" _msthash="183">We answer the most frequently asked questions about advertising on Gradimo Skupaj.at</h3>
                </div>
                <div class="schema-faq wp-block-yoast-faq-block">
                    <div class="faq_wrapper_1 faq_wrapper">
                        <div class="schema-faq-section wrap1" id="faq-question-1649859098705">
                            <strong class="schema-faq-question" _msttexthash="2427035" _msthash="184">Does advertising on Gradimo Skupaj.at still pay off in the age of Google?</strong> <p class="schema-faq-answer" _msttexthash="170371240" _msthidden="1" _msthash="185">Ganz klar: Ja!<br />Gradimo Skupaj.at ist das größte Unternehmensverzeichnis Österreichs mit mehr als 66 Millionen<sup>1</sup> Aufrufen im Jahr 2018. 10 Millionen<sup>1</sup> Neukund:innen werden jährlich durch Gradimo Skupaj.at akquiriert. Fast jede:r zweite:r Nutzer:in auf Gradimo Skupaj.at kontaktiert auch ein Unternehmen. Zudem ist Gradimo Skupaj.at auch auf Google eine der Top-Websites. Nur fünf Websites<sup>1</sup> haben in Österreich eine höhere Google-Sichtbarkeit als Gradimo Skupaj.at, darunter Wikipedia und Facebook.<br />Zusammengefasst gilt: Gradimo Skupaj.at ist die profitabelste Plattform zur Neukundengewinnung in Österreich!<br /><sup>1</sup> Gradimo Skupaj, 2020</p>
                        </div>
                        <div class="schema-faq-section wrap1" id="faq-question-1649859108537">
                            <strong class="schema-faq-question" _msttexthash="9501518" _msthash="186">I already have a free business listing on Gradimo Skupaj.at – why should I pay for a pre-ranking?</strong> <p class="schema-faq-answer" _msttexthash="95723355" _msthidden="1" _msthash="187">Hast du dich schon einmal dabei erwischt, auf Google auf die Ergebnisseite 2 zu klicken? Nein? 99 % der Konsumentinnen und Konsumenten klicken auf ein Suchergebnis der Seite 1<sup>1</sup>. Ähnlich ist das bei Gradimo Skupaj.at. Wenn du nicht möglichst weit vorne gereiht bist, hast du kaum eine Chance, kontaktiert zu werden. So erhält ein Premium-Ranking auf Gradimo Skupaj.at im Schnitt etwa fünf Mal so viele Klicks<sup>1</sup> wie ein kostenloser Firmeneintrag.<br /><sup>1</sup> Gradimo Skupaj, 2020</p> </div><div class="schema-faq-section wrap1" id="faq-question-1649859118916"><strong class="schema-faq-question" _msttexthash="2319005" _msthash="188">How do I know that a Gradimo Skupaj.at listing will bring me customers?</strong>
                            <p class="schema-faq-answer" _msttexthash="54453295" _msthidden="1" _msthash="189">Gradimo Skupaj.at ist völlig transparent: Du kannst alle messbaren Kontaktmaßnahmen direkt in deiner Gradimo Skupaj.at Kundenzone unter „Statistik“ betrachten. Im Gegensatz zu anderen Werbeformen weißt du so stets, wofür du dein Geld investierst.</p> </div><div class="schema-faq-section wrap1" id="faq-question-1649859127828"><strong class="schema-faq-question" _msttexthash="1052506" _msthash="190">How does pre-ranking work on Gradimo Skupaj.at?</strong> <p class="schema-faq-answer" _msttexthash="119751268" _msthidden="1" _msthash="191">Es gibt für jede Branche und abhängig von der gewählten Region verschiedene Kategorien, die die Reihung der Einträge bestimmt. Am höchsten eingestuft sind die Premium-Einträge, darunter folgen die Top- und Basis-Plus-Einträge. Ein Algorithmus bestimmt innerhalb der einzelnen Kategorien die Reihung der Unternehmen. Unsere Mitarbeiter:innen beraten dich gerne, welches Produkt sich für dein Geschäft am besten eignet, damit du das Meiste aus deinem Firmeneintrag herausholst.</p> </div></div>
                    <div class="faq_wrapper_2 faq_wrapper"><div class="schema-faq-section wrap2" id="faq-question-1649859133254"><strong class="schema-faq-question" _msttexthash="647296" _msthash="192">Which product is right for me?</strong> <p class="schema-faq-answer" _msttexthash="70472948" _msthidden="1" _msthash="193">Welches Produkt für dich geeignet ist, hängt von deiner Region, Branche und Unternehmensgröße ab. Bei kleinen Regionen mit wenig Konkurrenz reicht in den meisten Fällen ein Basis Plus-Ranking aus, wohingegen in urbanen Gebieten mit starker Konkurrenz ein Premium-Ranking zielführend sein kann. Kontaktiere unsere Expert:innen und lass dich unverbindlich beraten.</p> </div>
                        <div class="schema-faq-section wrap2" id="faq-question-1649859141908"><strong class="schema-faq-question" _msttexthash="4259450" _msthash="194">My company offers a very special service with which I want to be found. Is that possible?</strong> <p class="schema-faq-answer" _msttexthash="33435337" _msthidden="1" _msthash="195">Kein Problem! Zu jedem Branchen-Ranking kannst du dir mindestens 5 Stichwörter aussuchen, mit denen du ebenfalls in deiner Ranking-Kategorie gefunden wirst. So kannst du dich auch optimal für die Suche nach ganz speziellen Leistungen positionieren.</p> </div>
                        <div class="schema-faq-section wrap2" id="faq-question-1649859149003"><strong class="schema-faq-question" _msttexthash="1584206" _msthash="196">What information does my listing need to include?</strong> <p class="schema-faq-answer" _msttexthash="90723763" _msthidden="1" _msthash="197">Online-Nutzer:innen erwarten sich neben allen Kontaktdaten vor allem die korrekten Öffnungszeiten sowie die gebotenen Leistungen. Über die Gradimo Skupaj-Kundenzone kannst du mithilfe eines Fragebogens gezielt Angaben machen, die sich viele Konsumentinnen und Konsumenten erwarten. Zudem kannst du dort eine ausführliche Firmen-Beschreibung ergänzen oder adaptieren. Grundsätzlich gilt: Je mehr Info, desto besser.</p> </div>
                        <div class="schema-faq-section wrap2" id="faq-question-1649859155821"><strong class="schema-faq-question" _msttexthash="719862" _msthash="198">My data has changed. What can I do?</strong> <p class="schema-faq-answer" _msttexthash="20744698" _msthidden="1" _msthash="199">Unser Kundenservice steht dir gerne zur Verfügung und ändert deine Daten entsprechend ab. Bitte kontaktiere uns unter kundenservice@Gradimo Skupaj.at oder +43 2236 401 38133 (Servicezeiten: Mo-Do 8-17 Uhr, Fr 8-14 Uhr)</p>
                        </div>
                    </div>
                </div>
            </div>
        </>
    )
}